config/routes.rb
Rails.application.routes.draw do
  get 'creatures/index'

  root to: "creatures#index"

  get "/creatures", to: "creatures#index"
  get "/creatures/new", to: "creatures#new"
  post "/creatures", to: "creatures#create"
  get "/creatures/:id", to: "creatures#show", as: "creature"
  get "/creatures/:id/edit", to: "creatures#edit", as: "edit_creature"
  patch "/creatures/:id", to: "creatures#update"
   # the destroy route
  delete "/creatures/:id", to: "creatures#destroy"
end

app/models/creature.rb
class Creature < ActiveRecord::Base

  def make_request
    res = Typhoeus.get("www.google.com/search", {
        params: {
          q:  @name
        }
      })
    res.body
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
    render :index
  end

  def new
    @creature = Creature.new
    render :new
  end

  def create
    newCreature = params.require(:creature).permit(:name, :description)
    creature = Creature.create(newCreature)
    redirect_to creature_path(creature.id)
  end

  def show
    @creature = Creature.find(params[:id])
    render :show
  end

  def edit 
    @creature = Creature.find(params[:id])
    render :edit
  end


  def update
    creature = Creature.find(params[:id])
    creature_params = params.require(:creature).permit(:name, :description)
    creature.update(creature_params)
    redirect_to creature_path(creature)
  end


  def destroy
    creature = Creature.find(params[:id])
    creature.destroy
    redirect_to creatures_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/edit.html.erb
<%= form_for @creature do |f| %>

    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.text_area :description, placeholder: "Description" %>
    <%= f.submit "save creature" %>

<% end %>

app/views/creatures/index.html.erb
<% @creatures.each do |creature| %>

    <div>
        <div>
          <%= link_to creature.name, creature_path(creature.id) %>
        </div>
        Name: <%= creature.name %> <br>
        Description: <%=  creature.description %>
        <%= button_to "Delete", creature, method: :delete %>
    </div>

<% end %>

app/views/creatures/new.html.erb
<%= form_for @creature do |f| %>

    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.text_area :description, placeholder: "Description" %>
    <%= f.submit "save creature" %>

<% end %>

app/views/creatures/show.html.erb
    
    <%= link_to "EDIT", edit_creature_path( @creature) %>
    <div>

        Name: <%= @creature.name %> <br>
        Description: <%=  @creature.description %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BogApp2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>